version: "3.8"

services:
  database:
    container_name: database
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=book_store_backend
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=book_store_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: